### PR TITLE
Check that object conforms to protocol

### PR DESCRIPTION
**Pull request by Brain89**
@igrekde 

What do you think? This is useful if we have Assembly's interface like below

``` objectivec
- (id<ProtocolName1>)method1;
- (id<ProtocolName2>)method2;
```

### CODE REVIEW

**Comment by etolstoy** [comment]
@Brain89 thanks for contributing, this feature would be a nice addition!
I'm not sure that it;s convenient to separate methods accepting class as a parameter from methods accepting protocol. Have a look at `TyphoonTypeDescriptor` class in `Typhoon framework`. They don't explicitly specify what the `type` is. Maybe we can use the same approach.

**Comment by Brain89** [comment]
@igrekde I reworked the way to check that targetObject conforms to protocol. To do this I added **RamblerTyphoonAssemblyTestsTypeDescriptor** object. Also I fixed checking dependencies with protocols. Now we can test something like 

``` objectivec
- (id<ProtocolName1, ProtocolName2>)dependency1;
- (ClassName<ProtocolName3, ProtocolName4>)dependency2;
```

As well as, I updated ReadMe file.

**WARNING.**  I changed **RamblerTyphoonAssemblyTests** public interface. Previous methods for testing are deprecated now.

**Comment by etolstoy** [comment]
- @Beniamiiin

**Comment by etolstoy** [comment]
Everything seems fine for me. Fix merge conflicts please.

**Comment by Brain89** [comment]
Fixed
And I corrected object names in test example

**Comment by etolstoy** [comment]
Thanks a lot for a wonderful contribution! I'll release a new version today

**Pull request merged**
